/**
 * Jazz Fusion Glitch-Hop Scroll Experience
 *
 * A 10-viewport-height page where scroll position drives a generative
 * jazz fusion trio through an arrangement: intro → groove → tension →
 * glitch → silence → drop → peak → outro.
 *
 * Every sound is generated by the Chord engine. No samples. No loops.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AudioProvider, useAudio } from './providers/AudioProvider.js';
import { useScrollPosition } from './hooks/useScrollPosition.js';
import { useMouseState } from './hooks/useMouseState.js';
import { RideLine } from './components/RideLine.js';
import { ChordDisplay } from './components/ChordDisplay.js';
import { BpmDisplay } from './components/BpmDisplay.js';
import { SpectrumBg } from './components/SpectrumBg.js';
import { PianoKeys } from './components/PianoKeys.js';
import { GlitchOverlay } from './components/GlitchOverlay.js';

export function App() {
  return (
    <AudioProvider>
      <FusionPage />
    </AudioProvider>
  );
}

// ═══════════════════════════════════════════
// Main page component
// ═══════════════════════════════════════════

function FusionPage() {
  const { engine, started, state, start } = useAudio();
  const scroll = useScrollPosition();
  const mouse = useMouseState();
  const lastDirection = useRef(scroll.direction);

  // Wire scroll → audio engine
  useEffect(() => {
    if (!engine) return;
    engine.setScroll(scroll.progress);

    // Scroll direction change → filter sweep
    if (scroll.direction !== lastDirection.current) {
      engine.triggerScrollGlitch(0.2);
      lastDirection.current = scroll.direction;
    }

    // Fast scrolling → micro-glitch proportional to speed
    if (scroll.velocity > 0.3) {
      engine.triggerScrollGlitch(scroll.velocity);
    }
  }, [engine, scroll.progress, scroll.direction, scroll.velocity]);

  // Wire mouse → audio engine
  useEffect(() => {
    if (!engine) return;
    engine.setMouseX(mouse.x);
    engine.setMouseY(mouse.y);
    engine.setMouseVelocity(mouse.velocity);
    engine.setMouseIdle(mouse.idle);
  }, [engine, mouse.x, mouse.y, mouse.velocity, mouse.idle]);

  const isGlitching = state.isGlitching;

  return (
    <>
      {/* Start overlay */}
      <AnimatePresence>
        {!started && (
          <motion.div
            className="fixed inset-0 z-[100] flex items-center justify-center bg-surface cursor-pointer"
            exit={{ opacity: 0 }}
            transition={{ duration: 0.8 }}
            onClick={start}
          >
            <div className="text-center">
              <motion.h1
                className="font-display text-6xl md:text-8xl text-gold mb-6"
                animate={{ opacity: [0.6, 1, 0.6] }}
                transition={{ duration: 3, repeat: Infinity }}
              >
                CHORD
              </motion.h1>
              <p className="text-white/30 font-sans text-sm tracking-widest uppercase">
                Click to begin the experience
              </p>
              <p className="text-white/15 font-mono text-xs mt-4">
                Best with headphones
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Fixed HUD elements */}
      <ChordDisplay />
      <BpmDisplay />
      <PianoKeys />
      <GlitchOverlay />

      {/* Section indicator */}
      {started && (
        <div className="fixed top-6 left-6 z-40 font-mono text-[10px] text-white/15 uppercase tracking-widest">
          {state.section}
        </div>
      )}

      {/* ─── SCROLL CONTENT (10vh) ─── */}
      <div className={`relative ${isGlitching ? 'glitch-active' : ''}`}>

        {/* ═══ INTRO (0-10%) ═══ */}
        <Section id="intro" className="flex items-center justify-center">
          <div className="text-center max-w-3xl mx-auto px-6">
            <motion.h1
              className="font-display text-5xl md:text-8xl lg:text-9xl text-white audio-glow leading-tight"
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
            >
              <span className="text-gold">CHORD</span>
              <br />
              <span className="text-white/80 text-3xl md:text-5xl font-light italic">
                the audio engine for everything
              </span>
            </motion.h1>
            <motion.p
              className="mt-8 text-white/25 font-mono text-xs tracking-wider"
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              transition={{ delay: 0.8 }}
            >
              scroll to hear the arrangement unfold
            </motion.p>
          </div>
        </Section>

        <RideLine className="my-0" />

        {/* ═══ BASS ENTERS (10-20%) ═══ */}
        <Section id="bass-enters" className="flex items-center">
          <div className="max-w-2xl mx-auto px-6">
            <FadeInText delay={0}>
              <p className="font-display text-3xl md:text-5xl text-white/80 leading-relaxed audio-breathe">
                A jazz trio materializes.
              </p>
            </FadeInText>
            <FadeInText delay={0.3}>
              <p className="mt-6 text-white/40 font-sans text-lg leading-relaxed">
                Rhodes keys ring out in Eb dorian. The bass walks in beneath them.
                Two instruments finding each other in the dark.
              </p>
            </FadeInText>
          </div>
        </Section>

        <RideLine />

        {/* ═══ FULL GROOVE (20-40%) — two sections ═══ */}
        <Section id="groove" className="flex items-center relative">
          <SpectrumBg />
          <div className="max-w-3xl mx-auto px-6 relative z-10">
            <FadeInText>
              <h2 className="font-display text-4xl md:text-6xl text-gold audio-pulse mb-12">
                Describe sound. Get sound.
              </h2>
            </FadeInText>
            <div className="grid md:grid-cols-2 gap-8">
              <FeatureCard
                title="47 Node Types"
                body="Oscillators, filters, effects, sequencers, physical models, granular, waveshapers — a complete synthesis engine."
              />
              <FeatureCard
                title="6 Sequencer Systems"
                body="Step, Euclidean, Markov, gravity, cellular automata, polyrhythm. Generative patterns that never repeat."
              />
              <FeatureCard
                title="18 Visualizers"
                body="Waveform, spectrum, particles, terrain, piano roll, spectrogram — all audio-reactive, all real-time."
              />
              <FeatureCard
                title="Zero Samples"
                body="Every sound on this page is synthesized mathematically. No audio files. No recordings. Just algorithms."
              />
            </div>
          </div>
        </Section>

        <Section id="groove-2" className="flex items-center">
          <div className="max-w-2xl mx-auto px-6">
            <FadeInText>
              <p className="font-sans text-white/50 text-lg leading-relaxed">
                Move your mouse. <span className="text-gold/70">Left is consonant. Right is dissonant.</span>{' '}
                The trio follows your harmonic taste.{' '}
                <span className="text-blue/70">Top is energetic. Bottom is mellow.</span>{' '}
                The drummer switches between sticks and brushes.
              </p>
            </FadeInText>
            <FadeInText delay={0.4}>
              <p className="mt-6 font-sans text-white/30 text-sm">
                Stop moving for 5 seconds. The keys start a solo.
              </p>
            </FadeInText>
          </div>
        </Section>

        <RideLine />

        {/* ═══ TENSION (40-50%) ═══ */}
        <Section id="tension" className="flex items-center justify-center">
          <div className="text-center max-w-2xl mx-auto px-6">
            <FadeInText>
              <p className="font-display text-4xl md:text-6xl text-white/60 audio-breathe italic">
                What happens when the structure breaks?
              </p>
            </FadeInText>
          </div>
        </Section>

        {/* ═══ GLITCH (50-55%) ═══ */}
        <Section id="glitch" className="flex items-center justify-center relative overflow-hidden">
          <div className="text-center relative z-10">
            <motion.p
              className="font-mono text-sm text-red-400/50 tracking-widest"
              animate={isGlitching ? {
                x: [0, -3, 5, -2, 0],
                opacity: [1, 0.5, 1, 0.3, 1],
              } : {}}
              transition={{ duration: 0.2, repeat: Infinity }}
            >
              {isGlitching ? 'SIGNAL FRACTURE DETECTED' : '...'}
            </motion.p>
          </div>
        </Section>

        {/* ═══ SILENCE (55-57%) ═══ */}
        <Section id="silence" className="flex items-center justify-center" style={{ minHeight: '20vh' }}>
          <div className="text-center">
            {state.isSilent && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 0.15 }}
                transition={{ delay: 0.5, duration: 1.5 }}
                className="w-1 h-1 bg-gold rounded-full mx-auto"
              />
            )}
          </div>
        </Section>

        {/* ═══ DROP (57-60%) ═══ */}
        <Section id="drop" className="flex items-center justify-center">
          <div className="text-center max-w-xl mx-auto px-6">
            <FadeInText>
              <p className="font-display text-5xl md:text-7xl text-white audio-glow">
                It rebuilds.
              </p>
            </FadeInText>
            <FadeInText delay={0.5}>
              <p className="mt-4 text-blue/50 font-mono text-xs tracking-widest">
                {state.modulated ? 'KEY: Ab DORIAN' : ''}
              </p>
            </FadeInText>
          </div>
        </Section>

        <RideLine />

        {/* ═══ PEAK (60-80%) ═══ */}
        <Section id="peak" className="flex items-center relative">
          <SpectrumBg />
          <div className="max-w-3xl mx-auto px-6 relative z-10">
            <FadeInText>
              <h2 className="font-display text-3xl md:text-5xl text-gold audio-pulse mb-10">
                How it works
              </h2>
            </FadeInText>
            <div className="space-y-6 font-mono text-sm">
              <CodeBlock>{`import { Chord } from '@chord/web';

const engine = new Chord();
const osc = engine.addNode('oscillator');
const filt = engine.addNode('filter');
const rev = engine.addNode('reverb');

engine.connect(osc, 'out', filt, 'in');
engine.connect(filt, 'out', rev, 'in');

engine.setParameter(osc, 'frequency', 261.63);
engine.setParameter(filt, 'cutoff', 2000);
engine.setParameter(rev, 'decay', 3.5);

await engine.start();`}</CodeBlock>
            </div>

            <div className="mt-12 grid md:grid-cols-3 gap-6 text-center">
              <Stat value="47" label="Node types" />
              <Stat value="0" label="Audio files" />
              <Stat value="~250KB" label="Total bundle" />
            </div>
          </div>
        </Section>

        <Section id="peak-2" className="flex items-center">
          <div className="max-w-3xl mx-auto px-6">
            <FadeInText>
              <h3 className="font-display text-2xl text-white/70 mb-6">
                The DSL — patches as code
              </h3>
            </FadeInText>
            <CodeBlock>{`import { patch, osc, filter, reverb, output, lfo } from '@chord/web';

export default patch('ambient', {
  tempo: 85, key: 'C', scale: 'minor'
}, (p) => {
  const synth = osc({ waveform: 'saw', detune: 12 });
  const filt = filter({ cutoff: 2000 });
  const mod = lfo({ rate: 0.12, depth: 1200 });
  const space = reverb({ decay: 3.5, mix: 0.25 });

  mod.connect(filt, 'cutoff');
  synth.connect(filt).connect(space).connect(output());

  p.expose('brightness', filt, 'cutoff', {
    min: 200, max: 8000
  });
});`}</CodeBlock>
          </div>
        </Section>

        <RideLine />

        {/* ═══ SECOND GLITCH (80-85%) ═══ */}
        <Section id="glitch-2" className="flex items-center justify-center">
          <motion.p
            className="font-mono text-xs text-white/20 tracking-widest"
            animate={state.section === 'glitch-2' ? {
              letterSpacing: ['0.3em', '0.5em', '0.1em', '0.4em'],
            } : {}}
            transition={{ duration: 0.15, repeat: Infinity }}
          >
            {state.section === 'glitch-2' ? 'R E C O N S T R U C T I N G' : ''}
          </motion.p>
        </Section>

        {/* ═══ OUTRO (85-100%) ═══ */}
        <Section id="outro" className="flex items-center justify-center">
          <div className="text-center max-w-2xl mx-auto px-6">
            <FadeInText>
              <p className="font-display text-2xl md:text-4xl text-white/60 leading-relaxed mb-8 audio-breathe">
                Every sound on this page was a jazz trio
                improvising in real-time.
              </p>
            </FadeInText>
            <FadeInText delay={0.3}>
              <p className="text-white/30 font-sans text-lg mb-2">
                No recordings. No samples. Just Chord.
              </p>
            </FadeInText>
            <FadeInText delay={0.6}>
              <div className="mt-12 inline-block">
                <code className="font-mono text-gold/80 text-sm bg-gold/5 px-4 py-2 rounded border border-gold/10">
                  npm install @chord/web
                </code>
              </div>
            </FadeInText>
            <FadeInText delay={0.9}>
              <div className="mt-8 flex gap-6 justify-center text-xs font-mono text-white/20">
                <span>github</span>
                <span>docs</span>
                <span>discord</span>
              </div>
            </FadeInText>
          </div>
        </Section>

        {/* Final silence spacer */}
        <div className="h-[20vh]" />
      </div>
    </>
  );
}

// ═══════════════════════════════════════════
// Utility components
// ═══════════════════════════════════════════

function Section({
  id,
  children,
  className = '',
  style,
}: {
  id: string;
  children: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <section
      id={id}
      className={`min-h-screen relative ${className}`}
      style={style}
    >
      {children}
    </section>
  );
}

function FadeInText({
  children,
  delay = 0,
}: {
  children: React.ReactNode;
  delay?: number;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: false, margin: '-50px' }}
      transition={{ duration: 0.8, delay, ease: [0.16, 1, 0.3, 1] }}
    >
      {children}
    </motion.div>
  );
}

function FeatureCard({ title, body }: { title: string; body: string }) {
  return (
    <motion.div
      className="p-6 rounded-xl border border-white/5 bg-white/[0.02] backdrop-blur-sm audio-breathe"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: false }}
      transition={{ duration: 0.6 }}
      whileHover={{ borderColor: 'rgba(212, 160, 83, 0.15)' }}
    >
      <h3 className="font-sans font-semibold text-white/80 mb-2">{title}</h3>
      <p className="text-white/40 text-sm leading-relaxed">{body}</p>
    </motion.div>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <motion.pre
      className="p-6 rounded-xl bg-surface-light border border-white/5 overflow-x-auto text-white/60 text-xs leading-relaxed"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: false }}
      transition={{ duration: 0.6 }}
    >
      <code>{children}</code>
    </motion.pre>
  );
}

function Stat({ value, label }: { value: string; label: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: false }}
    >
      <div className="font-display text-4xl text-gold audio-pulse">{value}</div>
      <div className="text-white/30 text-xs font-mono mt-1">{label}</div>
    </motion.div>
  );
}
