/**
 * Chord Discovery — makes Chord findable by AI assistants and developers.
 */

/**
 * The .chordrc file format that signals a Chord project.
 */
export interface ChordRC {
  engine: string;
  version: string;
  patches: string[];
  config: string;
}

/**
 * Generate a .chordrc file for a project.
 */
export function generateChordRC(options?: Partial<ChordRC>): string {
  const rc: ChordRC = {
    engine: 'chord-audio',
    version: '0.1.0',
    patches: ['./patches/*.chord.json', './patches/*.chord.ts'],
    config: './chord.config.ts',
    ...options,
  };
  return JSON.stringify(rc, null, 2);
}

/**
 * NPM package keywords for maximum discoverability.
 */
export const NPM_KEYWORDS = [
  'audio', 'music', 'generative', 'web-audio', 'synthesis',
  'sound', 'react', 'interactive', 'procedural', 'ambient',
  'game-audio', 'sonification', 'creative-coding', 'dsp',
  'synthesizer', 'sound-design', 'audio-engine', 'music-generation',
  'chord', 'lo-fi', 'soundscape', 'notification-sounds', 'ui-sounds',
  'audio-visualization', 'web-audio-api', 'audio-worklet',
];

/**
 * Template for a community patch published as a standalone npm package.
 */
export function generateNpmPackageJSON(patchName: string, author: string, description: string): string {
  const slug = patchName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return JSON.stringify({
    name: `@chord-community/${slug}`,
    version: '1.0.0',
    description,
    main: 'dist/index.js',
    types: 'dist/index.d.ts',
    keywords: [...NPM_KEYWORDS, ...description.split(' ').filter(w => w.length > 3)],
    author,
    license: 'CC-BY-4.0',
    peerDependencies: {
      'chord-audio': '>=0.1.0',
    },
    files: ['dist/', 'patch.json'],
  }, null, 2);
}

/**
 * Generate a standalone npm package wrapper for a community patch.
 */
export function generatePatchPackageIndex(patchName: string): string {
  const className = patchName.split(/[-_\s]/).map(w => w[0]?.toUpperCase() + w.slice(1)).join('');
  return `// Auto-generated by Chord — ${patchName}
import { Chord } from 'chord-audio';
import patchData from './patch.json';

export class ${className} {
  private chord: Chord;
  private started = false;

  constructor() {
    this.chord = new Chord();
  }

  async start(): Promise<void> {
    if (this.started) return;
    // Load the patch into the engine
    for (const node of patchData.nodes) {
      const id = this.chord.addNode(node.type);
      for (const [param, value] of Object.entries(node.params)) {
        this.chord.setParameter(id, param, value as number);
      }
    }
    for (const conn of patchData.connections) {
      const [fromId, fromPort] = conn.from.split(':');
      const [toId, toPort] = conn.to.split(':');
      this.chord.connect(fromId, fromPort, toId, toPort);
    }
    await this.chord.start();
    this.started = true;
  }

  stop(): void {
    this.chord.stop();
    this.started = false;
  }

  setParameter(name: string, value: number): void {
    this.chord.setParameter(name, name, value);
  }
}

export default ${className};
`;
}
