//! Shared code generation utilities used across all export targets.
//!
//! Provides helpers for generating the common Rust DSP graph embedding code that every
//! target needs, plus target-specific dispatch.

use chord_audio_graph::{CompiledGraph, Graph};

use crate::types::{ExportArtifact, ExportError, ExportOptions, ExportTarget, OptimizationLevel};

/// Generate all code artifacts for the given target.
///
/// Dispatches to the appropriate target-specific exporter.
pub fn generate_artifacts(
    graph: &Graph,
    compiled: &CompiledGraph,
    options: &ExportOptions,
) -> Result<Vec<ExportArtifact>, ExportError> {
    match options.target {
        ExportTarget::Web => {
            crate::target::WebExporter::generate(graph, compiled, options)
        }
        ExportTarget::VST3 => {
            crate::target::Vst3Exporter::generate(graph, compiled, options)
        }
        ExportTarget::CLAP => {
            // CLAP is similar to VST3 — reuse the VST3 exporter with minor adjustments.
            crate::target::Vst3Exporter::generate_clap(graph, compiled, options)
        }
        ExportTarget::Standalone => {
            crate::target::StandaloneExporter::generate(graph, compiled, options)
        }
        ExportTarget::Desktop => {
            // Desktop is the same as Standalone with an optional GUI layer.
            crate::target::StandaloneExporter::generate(graph, compiled, options)
        }
        ExportTarget::GameEngine => {
            crate::target::GameEngineExporter::generate(graph, compiled, options)
        }
        ExportTarget::MobileFramework => {
            // Mobile uses the C API from the game engine exporter + platform-specific wrappers.
            crate::target::GameEngineExporter::generate_mobile(graph, compiled, options)
        }
    }
}

/// Generate the common Rust DSP graph code that is shared across all native targets.
///
/// This produces a Rust source string that embeds the graph's execution order, node
/// types, connections, and parameter defaults — everything needed to reconstruct and
/// run the graph at runtime without the original graph file.
pub fn generate_graph_embed_code(
    graph: &Graph,
    compiled: &CompiledGraph,
    options: &ExportOptions,
) -> String {
    let mut code = String::new();

    code.push_str("// Auto-generated by Chord export engine.\n");
    code.push_str("// Do not edit manually.\n\n");

    // Graph metadata.
    code.push_str(&format!(
        "pub const GRAPH_NAME: &str = {:?};\n",
        options.name
    ));
    code.push_str(&format!(
        "pub const SAMPLE_RATE: u32 = {};\n",
        options.sample_rate
    ));
    code.push_str(&format!(
        "pub const BUFFER_SIZE: u32 = {};\n",
        options.buffer_size
    ));
    code.push_str(&format!(
        "pub const NODE_COUNT: usize = {};\n",
        compiled.execution_order.len()
    ));
    code.push_str(&format!(
        "pub const BUFFER_COUNT: usize = {};\n\n",
        compiled.buffer_layout.buffer_count
    ));

    // Node execution order with types.
    code.push_str("/// Node types in execution order.\n");
    code.push_str("pub const NODE_TYPES: &[&str] = &[\n");
    for node_id in &compiled.execution_order {
        if let Some(node) = graph.node(node_id) {
            code.push_str(&format!("    {:?},\n", node.node_type));
        }
    }
    code.push_str("];\n\n");

    // Parameter defaults.
    code.push_str("/// Parameter defaults: (node_index, param_id, value, min, max).\n");
    code.push_str("pub const PARAMETER_DEFAULTS: &[(usize, &str, f64, f64, f64)] = &[\n");
    for (idx, node_id) in compiled.execution_order.iter().enumerate() {
        if let Some(node) = graph.node(node_id) {
            for param in &node.parameters {
                code.push_str(&format!(
                    "    ({}, {:?}, {:.6}, {:.6}, {:.6}),\n",
                    idx, param.id, param.default, param.min, param.max
                ));
            }
        }
    }
    code.push_str("];\n");

    code
}

/// Generate Cargo.toml content for an exported Rust project.
pub fn generate_cargo_toml(name: &str, optimization: OptimizationLevel) -> String {
    let mut toml = String::new();

    toml.push_str(&format!("[package]\nname = {:?}\nversion = \"0.1.0\"\nedition = \"2021\"\n\n", name));

    // Profile settings based on optimization level.
    match optimization {
        OptimizationLevel::Debug => {
            toml.push_str("[profile.dev]\nopt-level = 0\ndebug = true\n\n");
        }
        OptimizationLevel::Release => {
            toml.push_str("[profile.release]\nopt-level = 3\nlto = true\ncodegen-units = 1\n\n");
        }
        OptimizationLevel::Size => {
            toml.push_str("[profile.release]\nopt-level = \"s\"\nlto = true\ncodegen-units = 1\nstrip = true\n\n");
        }
    }

    toml
}
